# creating security group
InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh and http to client host
      GroupName: mysg
      VpcId: !Ref Vpc 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"  
  
# creating ec-instance
  MyEC2Instance:
    DependsOn: InstanceSecurityGroup 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-05ba3a39a75be1ec4
      KeyName: !Ref KeyPair
      InstanceType: t3a.small
      SecurityGroupIds:
            - !GetAtt InstanceSecurityGroup.GroupId
      #SecurityGroups: !Ref InstanceSecurityGroup 
      SubnetId: !Ref PublicSubnet1
# creating Key pair
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: mykey    
